# Site settings
title: Fotoradio
description: 'un podcast che parla di fotografie' # this means to ignore newlines until "baseurl:"
permalink: '/:year/:month/:title'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ws24.fotoradio.info" # the base hostname & protocol for your site, e.g. http://example.com
logo: "/assets/img/branding/fotoradio_logo2.svg"
logo-icon: "/assets/img/branding/fotoradio_ico.svg"
logo-icon-SEO: "/assets/img/branding/fotoradio_ico.png" # must be a non SVG file

# Night/Dark mode
# Default mode is "auto", "auto" is for auto nightshift
# (19:00 - 07:00), "manual" is for manual toggle, and
# "on/off" is for default on/off.
#
# Whatever the user's choice is, it will supersede the
# default setting of the site and be kept during the
# visit (session). Only the dark mode setting is "manual",
# it will be always kept on every visit (i.e. no matter
# the browser is closed or not)
night_mode: "on/off"

logo-dark: "/assets/img/branding/fotoradio_logo2.svg"
highlight_theme: syntax-base16.monokai.dark # select a dark theme for the code highlighter if needed

# Author settings
author: Fotoradio # add your name
author-pic: "/assets/img/branding/fotoradio_ico.png"
about-author: un podcast che parla di fotografie

# Contact links
email: fotoradio.info@gmail.com # Add your Email address
phone: # Add your Phone number
website: https://lazban.github.io/fotoradio23v07 # Add your website
# linkedin: amaynez # Add your Linkedin handle
# github: amaynez # Add your Github handle
# twitter: '@MvmThe' # Add your Twitter handle
# bandcamp: armandomaynez # Add your Bandcamp username
# stackoverflow: stackoverflow # Add your stackoverflow account

# Newsletter
# mailchimp: "https://github.us1.list-manage.com/subscribe/post?u=8ece198b3eb260e6838461a60&amp;id=397d90b5f4"

# Tracker
analytics: G-R8SZS2YBZK
fbadmin: ar.maybach

# Paginate
paginate: 4
paginate_path: 'page:num'
words_per_minute: 200

extensions:
  mermaid_enable: true

# Comments
comments: utteranc  #[disqus, utteranc]
comments_opts:
  comments_curtain: yes # leave empty to show the disqus embed directly
  repo: # The GitHub repo URL.  https://utteranc.es/
  issue_term: # The GitHub issue label
  label: # The GitHub comments label
  theme: # The GitHub comment's there. e.g. github-dark
  # Disqus
  discus_identifier: # Add your discus identifier

# Build settings
markdown: kramdown
mathjax: true
highlighter: rouge
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]

# Outputting
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

category_archive:
  type: liquid
  path: /categories/

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]
